const products = [
  {
    attributes_id: "1",
    product_ref_id: "1",
    attribute_type: "size",
    attribute_value: "S",
    vol_weight: "1",
    unit: "gm",
    attribute_weight_volume: "",
    attribute_delivery_unit: "",
    attributes_qty: "8",
    barcode: "356279684459700359.png",
    barcode_value: "356279684459700359",
    attribute_best_before_date: "",
    attribute_product_delivery_by: "",
    product_attribute_images: "",
    product_attribute_mrp_price: "100",
    product_attribute_incs_price: "0",
    product_attribute_gst_value: "0",
    product_attribute_cal_discount: "0",
    product_attribute_selling_price: "102",
    product_attribute_deal_in: "0",
    product_attribute_deal_price: "0",
    product_attribute_deal_discount: "0",
    product_attribute_deal_selling_price: "0",
    product_attribute_deal_status: "0",
    attribute_default_value: "default",
    attribute_partner_product: "",
    attributes_crt_date: "2022-03-15 13:50:13",
    attributes_mod_date: "2022-03-15 13:50:13",
    attributes_qty_mod_date: "2022-03-15 13:50:13",
    attribute_deal_set_date: null,
    attribute_deal_approve_date: null,
    attribute_deal_reject_date: null,
    attributes_deal_mod_at: null,
    attribute_status: "1",
    new_attribute_quantity_added_at: "2022-03-15 08:42:32",
    new_attribute_quantity_edit_at: "",
    pro_attribute_crated_by_admin_for_vendor: "",
    pro_attribute_crated_by_admin_for_vendor_at: "",
    pro_attributes_crated_by_admin_for_vendor: "",
    pro_attributes_crated_by_admin_for_vendor_at: "",
    product_id: "1",
    s_id: "1",
    bar_code_status: "0",
    vendor_bar_code: "",
    parent_cat_id: "1",
    sub_cat_id: "2",
    child_cat_id: "16",
    product_name: "demo product",
    collection_name: "demo product collection",
    store_name: "delhi",
    product_description: "demo product description",
    product_main_image: "6169.jpg",
    product_specification_imgs: "214.png,6170.jpg",
    product_HSN_number: "123456",
    product_ISIN_number: "0",
    length: "",
    width: "",
    height: "",
    product_gtin_number: "",
    vendor_ref_id: "0",
    vendor_ref_mobile: "",
    product_delivery_by: "",
    product_brand_name: "brand_name",
    product_mgf_data: "",
    produc_expiry_date: "",
    product_qty: "0",
    product_mrp_price: "0",
    product_incs_price: "0",
    product_gst: "5",
    product_gst_value: "0",
    product_selling_price: "0",
    product_deal_price: "0",
    product_deal_selling_price: "0",
    product_discount: "0",
    product_deal_discount: "0",
    product_deals_in: "0",
    product_deal: "",
    region_ids: "1",
    excluded_pincodes: "",
    included_pincodes: "",
    product_status: "0",
    reject_reson: "",
    action_on_rejaction: "",
    product_deal_status: "0",
    product_crt_date: "2022-03-15 13:50:12",
    product_mod_date: "2022-03-15 13:50:12",
    product_quantity_date: "2022-03-15 13:50:12",
    product_deal_set_date: "2022-03-15 13:50:12",
    product_deal_status_date: "2022-03-15 13:50:12",
    product_deal_mod_at: "2022-03-15 13:50:12",
    product_cancel_at: "",
    product_reject_at: "",
    product_approve_at: "",
    product_reapprove_request_sent_at: "2022-03-15 13:50:12",
    dealproduct_reject_at: "2022-03-15 13:50:12",
    product_search_keywords: "demo product ",
    pro_crated_by_admin_for_vendor: "",
    pro_crated_by_admin_for_vendor_at: "",
  },
  {
    attributes_id: "17",
    product_ref_id: "11",
    attribute_type: "size",
    attribute_value: "S",
    vol_weight: "1",
    unit: "kg",
    attribute_weight_volume: "",
    attribute_delivery_unit: "",
    attributes_qty: "8",
    barcode: "356189505079313141.png",
    barcode_value: "356189505079313141",
    attribute_best_before_date: "",
    attribute_product_delivery_by: "",
    product_attribute_images: "",
    product_attribute_mrp_price: "700",
    product_attribute_incs_price: "0",
    product_attribute_gst_value: "0",
    product_attribute_cal_discount: "0",
    product_attribute_selling_price: "714",
    product_attribute_deal_in: "0",
    product_attribute_deal_price: "0",
    product_attribute_deal_discount: "0",
    product_attribute_deal_selling_price: "0",
    product_attribute_deal_status: "0",
    attribute_default_value: "default",
    attribute_partner_product: "",
    attributes_crt_date: "2022-03-19 15:21:12",
    attributes_mod_date: "2022-03-19 15:21:12",
    attributes_qty_mod_date: "2022-03-19 15:21:12",
    attribute_deal_set_date: null,
    attribute_deal_approve_date: null,
    attribute_deal_reject_date: null,
    attributes_deal_mod_at: null,
    attribute_status: "1",
    new_attribute_quantity_added_at: "2022-03-19 10:08:00",
    new_attribute_quantity_edit_at: "",
    pro_attribute_crated_by_admin_for_vendor: "",
    pro_attribute_crated_by_admin_for_vendor_at: "",
    pro_attributes_crated_by_admin_for_vendor: "",
    pro_attributes_crated_by_admin_for_vendor_at: "",
    product_id: "11",
    s_id: "3",
    bar_code_status: "0",
    vendor_bar_code: "",
    parent_cat_id: "1",
    sub_cat_id: "2",
    child_cat_id: "15",
    product_name: "testingasd",
    collection_name: "testingasd collection",
    store_name: "delhi",
    product_description: "testingasd description",
    product_main_image: "112.png",
    product_specification_imgs: "113.png,221.png",
    product_HSN_number: "132456",
    product_ISIN_number: "0",
    length: "",
    width: "",
    height: "",
    product_gtin_number: "",
    vendor_ref_id: "0",
    vendor_ref_mobile: "",
    product_delivery_by: "",
    product_brand_name: "brand_name",
    product_mgf_data: "",
    produc_expiry_date: "",
    product_qty: "0",
    product_mrp_price: "0",
    product_incs_price: "0",
    product_gst: "0",
    product_gst_value: "0",
    product_selling_price: "0",
    product_deal_price: "0",
    product_deal_selling_price: "0",
    product_discount: "0",
    product_deal_discount: "0",
    product_deals_in: "0",
    product_deal: "",
    region_ids: "1",
    excluded_pincodes: "",
    included_pincodes: "",
    product_status: "0",
    reject_reson: "",
    action_on_rejaction: "",
    product_deal_status: "0",
    product_crt_date: "2022-03-19 15:21:12",
    product_mod_date: "2022-03-19 15:21:12",
    product_quantity_date: "2022-03-19 15:21:12",
    product_deal_set_date: "2022-03-19 15:21:12",
    product_deal_status_date: "2022-03-19 15:21:12",
    product_deal_mod_at: "2022-03-19 15:21:12",
    product_cancel_at: "",
    product_reject_at: "",
    product_approve_at: "",
    product_reapprove_request_sent_at: "2022-03-19 15:21:12",
    dealproduct_reject_at: "2022-03-19 15:21:12",
    product_search_keywords: "testingasd",
    pro_crated_by_admin_for_vendor: "",
    pro_crated_by_admin_for_vendor_at: "",
  },
];

products[0].product_id;

const Products = [
  {
    attributes_id: "1",
    product_ref_id: "1",
    attribute_qty_id: "1",
    attribute_type: "dimensions",
    attribute_value: "16 *16*61",
    vol_weight: "1000",
    unit: "",
    attribute_weight_volume: "",
    attribute_delivery_unit: "",
    attributes_qty: "18",
    barcode: "356127463321505910.png",
    barcode_value: "356127463321505910",
    attribute_best_before_date: "",
    attribute_product_delivery_by: "",
    product_attribute_images: "cdce76a5d7bea33e8e99421d458365ae.jpg",
    product_attribute_mrp_price: "5000",
    product_attribute_incs_price: "4000",
    product_attribute_gst_value: "0",
    product_attribute_cal_discount: "0",
    product_attribute_selling_price: "5250",
    product_attribute_deal_in: "0",
    product_attribute_deal_price: "0",
    product_attribute_deal_discount: "0",
    product_attribute_deal_selling_price: "5249",
    product_attribute_deal_status: "1",
    attribute_default_value: "default",
    attribute_partner_product: "",
    attributes_crt_date: "2022-04-09 10:13:11",
    attributes_mod_date: "2022-04-09 10:13:11",
    attributes_qty_mod_date: "2022-04-09 10:13:11",
    attribute_deal_from_date: "2022-04-09",
    attribute_deal_to_date: "2022-04-29",
    attribute_deal_id: "1",
    attribute_status: "1",
    new_attribute_quantity_added_at: "2022-04-09 04:54:22",
    new_attribute_quantity_edit_at: "",
    pro_attribute_crated_by_admin_for_vendor: "",
    pro_attribute_crated_by_admin_for_vendor_at: "",
    pro_attributes_crated_by_admin_for_vendor: "",
    pro_attributes_crated_by_admin_for_vendor_at: "",
    product_id: "1",
    s_id: "1",
    bar_code_status: "0",
    vendor_bar_code: "",
    parent_cat_id: "Home",
    sub_cat_id: "D?cor",
    child_cat_id:
      "Decorative Trays & Boxes,Picture Frames,Vases,Jars & Canisters,Wall & Home Accents,Garden Accessorie",
    product_name: "Lamp",
    collection_name: "Home Decorr",
    store_name: "delhi",
    product_description: "Triple fold Nickel 2757 with Drum shaped Beige Shade",
    product_main_image: "bd21ff22e68f76ce55ba45efedc11041.jpg",
    product_specification_imgs:
      "ef88a41940c4580bb7ea5b478613abaa.jpeg,f352d3b8bebec0ef504de974df022f2f.jpeg,adaa562ed1cd06bf12f58c303395361f.jpeg",
    product_HSN_number: "123456",
    product_ISIN_number: "0",
    length: "",
    width: "",
    height: "",
    product_gtin_number: "",
    vendor_ref_id: "0",
    vendor_ref_mobile: "",
    product_delivery_by: "",
    product_brand_name: "brand_name",
    product_mgf_data: "",
    produc_expiry_date: "",
    product_qty: "0",
    product_mrp_price: "0",
    product_incs_price: "0",
    product_gst: "5",
    product_gst_value: "0",
    product_selling_price: "0",
    product_deal_price: "0",
    product_deal_selling_price: "0",
    product_discount: "0",
    product_deal_discount: "0",
    product_deals_in: "0",
    product_deal: "",
    region_ids: "1",
    excluded_pincodes: "",
    included_pincodes: "",
    product_status: "0",
    reject_reson: "",
    action_on_rejaction: "",
    product_deal_status: "0",
    product_crt_date: "2022-04-09 10:13:11",
    product_mod_date: "2022-04-09 10:13:11",
    product_quantity_date: "2022-04-09 10:13:11",
    product_deal_set_date: "2022-04-09 10:13:11",
    product_deal_status_date: "2022-04-09 10:13:11",
    product_deal_mod_at: "2022-04-09 10:13:11",
    product_cancel_at: "",
    product_reject_at: "",
    product_approve_at: "",
    product_reapprove_request_sent_at: "2022-04-09 10:13:11",
    dealproduct_reject_at: "2022-04-09 10:13:11",
    product_search_keywords:
      "Lamp,Table lamp, side lamp,bed side table lamp, brighting lamp, lamp",
    pro_crated_by_admin_for_vendor: "",
    pro_crated_by_admin_for_vendor_at: "",
  },
];
products[0].product_deal;

const cat = [
  {
    parent_category_id: "1",
    parent_category_name: "Apparel",
    parent_category_img: "",
    parent_category_status: "Active",
    parent_category_crt_date: "0000-00-00 00:00:00",
    parent_category_mod_date: "0000-00-00 00:00:00",
  },
  {
    parent_category_id: "2",
    parent_category_name: "Jewelry",
    parent_category_img: "",
    parent_category_status: "Active",
    parent_category_crt_date: "0000-00-00 00:00:00",
    parent_category_mod_date: "0000-00-00 00:00:00",
  },
  {
    parent_category_id: "3",
    parent_category_name: "Accessories",
    parent_category_img: "",
    parent_category_status: "Active",
    parent_category_crt_date: "0000-00-00 00:00:00",
    parent_category_mod_date: "0000-00-00 00:00:00",
  },
  {
    parent_category_id: "4",
    parent_category_name: "Home",
    parent_category_img: "",
    parent_category_status: "Active",
    parent_category_crt_date: "0000-00-00 00:00:00",
    parent_category_mod_date: "0000-00-00 00:00:00",
  },
  {
    parent_category_id: "5",
    parent_category_name: "Personal Care",
    parent_category_img: "",
    parent_category_status: "Active",
    parent_category_crt_date: "0000-00-00 00:00:00",
    parent_category_mod_date: "0000-00-00 00:00:00",
  },
];
